# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jsons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('now_price', models.CharField(max_length=60)),
                ('old_price', models.CharField(max_length=60)),
                ('discount', models.CharField(max_length=30)),
                ('price_discount', models.CharField(max_length=11)),
                ('src', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Slideer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
